Pull into main feature/cards
taed2-2425q1-gced-upc/TAED2_Mates pull request #3
Opened 2024-09-22 18:11 UTC by mariatubella

2024-09-23 07:52 UTC, 0J0P0 requested changes
Lo veo bien. Tambien pondria la cita de la paguina de kaggle en el apartado de **Citations**

Solo es la del modelo no? Diria que falta la del dataset igual.

2024-09-24 16:37 UTC, 0J0P0 commented on docs/n02085620_3045.jpg
No es urgente, pero le cambiaria el nombre a esta imagen para que sea example.jpg. A menos que expliques el porque del nombre

2024-09-24 16:45 UTC, 0J0P0 commented on docs/Dataset_card.md
@mariatubella mirate tmb los otros repositorios, en algunos puedes encontrar algun ejemplo de como han hecho ellos los cards.

Estos por ejemplo tienen mas cosas, no se que aplique y que no, habria que mirar. https://github.com/taed2-2425q1-gced-upc/TAED2_DataExplorers/blob/main/docs/dataset_card.md

2024-09-24 16:47 UTC, 0J0P0 requested changes
Mirarse sobre todo los detalles del dataset como lo han hecho en otros repos.

2024-09-24 16:59 UTC, 0J0P0 commented on docs/Dataset_card.md
Por ejemplo aqui tmb ponen un poco mas de info de los datos: https://www.kaggle.com/competitions/dog-breed-identification/data

2024-09-24 18:01 UTC, 0J0P0 commented on docs/Dataset_card.md
Tambien, del modelo, hay varias versiones y para diferentes objetivos. Aqui por ejemplo estamos usando solo para un uso de clasificacion con version 135-228.

2024-09-25 16:29 UTC, mariatubella commented
este grupo lo que tiene colgado es el template :(((

Missatge de JP ***@***.***> del dia dt., 24 de set. 2024 a
les 18:45:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> On docs/Dataset_card.md
> <https://github.com/taed2-2425q1-gced-upc/TAED2_Mates/pull/3#discussion_r1773701569>
> :
>
> @mariatubella <https://github.com/mariatubella> mirate tmb los otros
> repositorios, en algunos puedes encontrar algun ejemplo de como han hecho
> ellos los cards.
>
> Estos por ejemplo tienen mas cosas, no se que aplique y que no, habria que
> mirar.
> https://github.com/taed2-2425q1-gced-upc/TAED2_DataExplorers/blob/main/docs/dataset_card.md
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/taed2-2425q1-gced-upc/TAED2_Mates/pull/3#pullrequestreview-2325842642>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZNHNJMGPGXIUXAGOWCFRBDZYGJKFAVCNFSM6AAAAABOUYPAG2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGMRVHA2DENRUGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-09-25 21:24 UTC, 0J0P0 approved these changes
perf

2024-09-26 11:03 UTC, AndreaTomas00 approved these changes
perfect

2024-09-26 12:33 UTC, merged