Feature/cards
taed2-2425q1-gced-upc/TAED2_Mates pull request #8
Opened 2024-09-29 16:30 UTC by mariatubella

Add dataset card to main

2024-09-29 17:30 UTC, 0J0P0 requested changes
Mirar faltas de ortografia y escritura

2024-09-29 17:30 UTC, 0J0P0 commented on docs/Dataset_card.md
> +- ```mobilenet_v2```: The dataset can be used to train the model [Mobilenet v2](https://www.kaggle.com/models/google/mobilenet-v2), which consists of an SSD-based object detection model trained on Op
En si el dataset puede servir para muchas tareas con varios propositos o modelos. Yo pondria mas una linea general diciendo eso.  

Sobre todo ademas comentar que se usa en la competencia de Kaggle https://www.kaggle.com/competitions/dog-breed-identification/overview (que es de donde lo sacamos lol). 


![image](https://github.com/user-attachments/assets/66b1cc7b-e374-4d05-852d-3b48642d0ed0)

En esta foto estan los dos modelos que se usan en la competencia. 

![image](https://github.com/user-attachments/assets/aa8da614-9392-4e41-9bd3-30a61909f16e)

y aqui los detalles de la competencia

2024-09-29 17:30 UTC, 0J0P0 commented on docs/Dataset_card.md
> +The source data are images of different breed dogs in diverse contexts and situations, which allows a more wide representation of the animal.
different dogs breed

2024-09-29 17:30 UTC, 0J0P0 commented on docs/Dataset_card.md
> +The source data are images of different breed dogs in diverse contexts and situations, which allows a more wide representation of the animal.
allows for a

2024-09-29 17:30 UTC, 0J0P0 commented on docs/Dataset_card.md
> +The source data are images of different breed dogs in diverse contexts and situations, which allows a more wide representation of the animal.
wider

2024-09-29 17:30 UTC, 0J0P0 commented on docs/Dataset_card.md
> +However, we cannot state if this identification falls under the concept of sensitive information.
no hay una definicion de lo que es sensitive information? Igual asi puedes definir si el dataset contiene o no

2024-09-29 17:30 UTC, 0J0P0 commented on docs/Dataset_card.md
> +- **Animal Welfare and Breed Identification**: This dataset can help in accurately identifying dog breeds, which could assist shelters, vets, and animal control in quickly recognizing lost or stray d
Quitale los titulos a los puntos que parece hecho de gpt lol

2024-09-29 17:30 UTC, 0J0P0 commented on docs/Dataset_card.md
> +If the dataset is unbalanced, the model might perform better on frequently represented breeds, leading to biased results. Related with that and geographically speaking, it may favor dog breeds that a
Mirate el codigo de experiments/eda porque hay estuve mirando un poco eso del imbalance. Y asi puedes poner aqui cifras

2024-09-30 11:50 UTC, 0J0P0 commented on docs/Dataset_card.md
> +The dataset contains, indeed, identitiy categories. However, we cannot state that this identification falls under the concept of sensitive information as these categories do not refer to humans.
identititititit

2024-09-30 11:51 UTC, 0J0P0 approved these changes

2024-10-01 09:57 UTC, AndreaTomas00 approved these changes

2024-10-01 10:00 UTC, merged